name: 'Setup Node.js'
description: 'Set up a specific version of Node.js and add the command-line tools to the PATH'
author: 'GitHub'
inputs:
  always-auth:
    description: 'Set always-auth in npmrc'
    default: 'false'
  node-version:
    description: 'Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0'
    default: '10.x'
  registry-url:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN'
  scope:
    description: 'Optional scope for authenticating against scoped registries'
# Deprecated option, do not use. Will not be supported after October 1, 2019
  version:
    description: 'Deprecated. Use node-version instead. Will not be supported after October 1, 2019'
    deprecationMessage: 'The version property will not be supported after October 1, 2019. Use node-version instead'
runs:
  using: 'node12'
  main: 'lib/setup-node.js'
